baseurl = "https://twoscompany.github.io/"
title = "Dating Service Auckland | Dating Agency | Introduction Agency"

theme = "hugo-universal-theme"
languageCode = "en-nz"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink = "/blog/"
    author = "shorter.david@gmail.com"
    defaultDescription = "Take the effort out of meeting eligible, professional single people, with Two's Company Dating Agency - Auckland's most selective dating service."
    defaultKeywords = ["dating", "singles", "introductions", "dating service", "dating agency", "introduction agency", "internet dating", "auckland", "auckland dating", "personal dating", "personal introductions", "new zealand dating", "men", "women", "best dating agency", "matchmaker", "match making", "meeting people", "professional", "personals", "love", "adult dating agencies", "sites", "romance"]

    # Style options: default (light-blue)", blue", green", marsala", pink", red", turquoise", violet
    style = "gold"

    # Google Maps license key
    googleMapsApiKey = "AIzaSyDF8vBLs65S2T_cOtVuZxxKcf5Gs2bYu9w"

    # Since this template is static", the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "shorter.david@gmail.com"
    about_us = "<p>Two's Company Dating Agency is Auckland's most selective dating service, dedicated to personalised matchmaking and introduction services for professional singles since 2003.</p>"
    copyright = "Copyright (c) 2003 - 2017, Two's Company LTD; all rights reserved."
    date_format = "2006-01-02"
    contacttext = "Enquire Now"
    logo = "img/logo.png"
    address = """<p><strong>Two's Company</strong>
        <br>Phone : 0800 021 522
        <br>Mobile : 021 522 922 
        <br>Email : <a href="mailto:sasha@twoscompany.co.nz?Subject=twoscompany%20query" target="_top">sasha@twoscompany.co.nz</a>
      </p>
      """
    latitude = "-36.871644"
    longitude = "174.7772232"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Success Stories"
    url  = "/stories/"
    weight = 1

[[menu.main]]
    name = "Press"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    url  = "/faq/"
    weight = 3
    
[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Success Stories"
    subtitle = "We check in with our clients after three months of being together and again after six months. This is what our clients are saying about us."
    link_url = "/stories/"
    link_text = "Success Stories"
    link_description = "Click here to read about other people just like you who we have helped to meet someone special."

[params.see_more]
    enable = true
    icon = "fa fa-venus-mars"
    title = "Do you want to join now?"
    subtitle = "Nothing happens to a person who does nothing. Tired of playing the dating game? Let us do the hard work for you, so you can focus on what dating should be about - having fun!"
    link_url = "/contact/"
    link_text = "Join Now"
    link_description = "Join Now"
	
[params.header]
    enable = true
    title = "Finding life partners for the world’s most exceptional people"
    link_url = "/contact/"
    link_text = "Enquire Now"
	link2_url = "https://youtu.be/-AC75mxHQFA"
    link2_text = "View Video"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "As featured in"
    subtitle = ""

[params.recent_posts]
    enable = false
	enableFooter = true
    title = "Latest News"
    subtitle = "Check out what the media is saying about Introduction Agency - Two's Company, Aucklands most respected Dating Agency since 2003"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"